/**
 * @fileoverview Generated by Jackbone.gap
 * DO NOT MODIFY
 */
requirejs.config({
    baseUrl: 'js',

    paths: {
        // Libraries
        jquery:       'libs/jquery/jquery',
        underscore:   'libs/underscore/underscore',
        lodash:       'libs/lodash/lodash',
        backbone:     'libs/backbone/backbone',
        jquerymobile: 'libs/jquery.mobile/jquery.mobile',
        handlebars:   'libs/handlebars/dist/handlebars',
        qunit:        'libs/qunitjs/qunit/qunit',
        testflight:   'libs/testflight',
        sqlite:       'libs/sqlite',
        kinetic:      'libs/kinetic',
        stacktrace:   'libs/stacktrace-js/stacktrace',
        jackbone:     'libs/jackbone/jackbone'
    },

    shim: {
        underscore: {
            exports: '_'
        },
        backbone: {
            deps: ["underscore", "jquery"],
            exports: "Backbone"
        },
        jquerymobile: {
            deps: ["jquery"]
        },
        jackbone: {
            deps: ["backbone", "jquerymobile"],
            exports: "Jackbone"
        },
        handlebars: {
            exports: 'Handlebars'
        },
        qunit: {
            exports: 'QUnit'
        },
        kinetic: {
            exports: 'Kinetic'
        },
        stacktrace: {
            exports: 'printStackTrace'
        },
    }
});

require([
    'jackbone',
    'cdv',
    'tests/testing',
    'logger'
],
function(Jackbone, Cordova, Testing, Logger) {

    function onDeviceReady() {
        
        Logger.initialize();
        Cordova.initialize();

        var onResume = function() {
            Jackbone.ViewManager.reSetupCurrent();
        };
        document.addEventListener("resume", onResume, false);

        if (Jackbone.main) {
            Jackbone.main(testingEnabled);
        }

        if (testingEnabled) {
            Testing.run();
        }
    }
    
    if (window.cordova) // PhoneGap / Cordova
        document.addEventListener("deviceready", onDeviceReady, false);
    else
        onDeviceReady();
});

