#!/bin/bash
#

command=$1
target=$2

function error() {
    test -e $EFILE && cat $EFILE
    echo
    echo "[ERROR] $1"
    echo
    exit  1
}

function usage {
    echo "usage: $0 <command>"
    echo "commands:"
    echo
    echo " - boilerplate"
    echo "            Create a new Jackbone.gap project in current directory."
    echo
    echo " - init     "
    echo "            Download dependencies."
    echo
    echo " - build    "
    echo "            Compile the project."
    echo
    echo " - run      "
    echo "            TODO."
    echo
    echo " - archive  "
    echo "            TODO."
    echo
    echo " - clean    "
    echo "            TODO."
    echo
    echo " - upload   "
    echo "            TODO."
    echo
    echo " - version  "
    echo "            Read and adjust version number from your VERSION file."
    echo
    echo " - help"
    echo "            show this help message."
    echo
    echo "Type '$0 <command> help' for more help on a specific command"
    echo
    exit 1
}

function checkNeededFiles() {
    test -e $PROJECT_PATH/config || error "config file is missing, create one from config-sample."
    test -e $PROJECT_PATH/assets/Default.png || error "assets/Default.png is missing (should be a 2048x2048 image)."
    test -e $PROJECT_PATH/assets/Icon.png || error "assets/Icon.png is missing (should be a 2048x2048 image)."
    n=`ls -1 $PROJECT_PATH/app/html/ | wc -l`
    [ $n -gt 0 ] || error "Please add your handlebars templates into app/html (at least one is needed)"

#    if [ "x$target" = "xios" ]; then
#        test -e $PROJECT_PATH/ios/Info.plist
#    fi
}

export PROJECT_PATH="`pwd`"
cd `dirname $0`
export JACKBONEGAP_PATH="`pwd`"

script="scripts/$command.sh"
test -e $script || usage

export DOWNLOADS_PATH="$PROJECT_PATH/.downloads"
export LIBS_PATH="$PROJECT_PATH/libs"
export JS_LIBS_PATH="$PROJECT_PATH/app/js/libs"
export EFILE="$PROJECT_PATH/build/tmp/jackbone.out"

if [ x$command != xboilerplate ]; then
    checkNeededFiles
    . $PROJECT_PATH/config

    if [ "x$PROJECT_NAME" = "x" ]; then
        error "config file should specify a project name."
    fi
fi

. $script $@ || exit 1
