#!/bin/bash
#
# Create an IPA Archive
#

set -e
source config

XCODE_VER=$(xcodebuild -version | head -n 1 | sed -e 's/Xcode //')
XCODE_MIN_VERSION="4.5"

if [[ "$XCODE_VER" < "$XCODE_MIN_VERSION" ]]; then
	echo "Cordova can only run in Xcode version $XCODE_MIN_VERSION or greater."
	exit 1
fi

CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd -P)
PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)

PROVISIONING_PROFILE="$PROJECT_PATH/../$PROVISIONING_PROFILE"

cd "$PROJECT_PATH"

xcodebuild -project $PROJECT_NAME.xcodeproj -sdk iphoneos -arch "armv7" -target $PROJECT_NAME -configuration Release clean build VALID_ARCHS="armv7" CONFIGURATION_BUILD_DIR="$PROJECT_PATH/build"

# Check if build succeeded
if [ $? != 0 ]
then
  exit 1
fi

/usr/bin/xcrun -sdk iphoneos PackageApplication -v "$PROJECT_PATH/build/$PROJECT_NAME.app" -o "$PROJECT_PATH/build/$PROJECT_NAME.ipa" --sign "${DEVELOPER_NAME}" --embed "${PROVISIONING_PROFILE}"
